#!/usr/bin/env python3
"""Generate default-implementation base classes for the D3D9 COM interfaces.

Each IDirect3D*9 interface in the vendored mingw d3d9.h is a struct of pure
virtual methods listed in vtable order (inherited methods repeated). For every
interface this emits a base class that overrides all of them: AddRef/Release
keep a reference count, QueryInterface refuses, and everything else reports the
call as unimplemented once and returns a failure/zero value. The Apple D3D9
classes derive from these and override only what the engine uses.
"""
import pathlib, re, sys

root = pathlib.Path(__file__).resolve().parent
header = (root / '../compat/native/directx/d3d9.h').resolve()
out = root / 'generated' / 'd3d9_default_bases.h'

INTERFACES = [
    'IDirect3D9', 'IDirect3DDevice9', 'IDirect3DSwapChain9', 'IDirect3DSurface9', 'IDirect3DVolume9',
    'IDirect3DVertexBuffer9', 'IDirect3DIndexBuffer9', 'IDirect3DTexture9', 'IDirect3DCubeTexture9',
    'IDirect3DVolumeTexture9', 'IDirect3DVertexDeclaration9', 'IDirect3DVertexShader9',
    'IDirect3DPixelShader9', 'IDirect3DQuery9', 'IDirect3DStateBlock9',
]

text = header.read_text(errors='replace')
method_re = re.compile(r'STDMETHOD(?:_\(\s*(?P<ret>[^,]+?)\s*,\s*(?P<name>\w+)\s*\)|\(\s*(?P<name2>\w+)\s*\))\s*\((?P<args>.*?)\)\s*PURE\s*;', re.S)

def parse(iface):
    m = re.search(r'DECLARE_INTERFACE_\(\s*%s\s*,\s*\w+\s*\)\s*\{(.*?)\n\};' % re.escape(iface), text, re.S)
    if not m:
        sys.exit(f'interface {iface} not found')
    methods = []
    for mm in method_re.finditer(m.group(1)):
        ret = (mm.group('ret') or 'HRESULT').strip()
        name = mm.group('name') or mm.group('name2')
        args = ' '.join(mm.group('args').split())
        args = re.sub(r'^THIS_\s*', '', args)
        args = '' if args == 'THIS' else args
        methods.append((ret, name, args))
    return methods

def default_return(ret):
    if ret == 'void':
        return None
    if ret == 'HRESULT':
        return 'D3DERR_INVALIDCALL'
    return '{}'

lines = [
    '// Generated by ports/ios/d3d9/generate_d3d9_bases.py from the vendored d3d9.h.',
    '// Do not edit by hand: rerun the script instead.',
    '#pragma once',
    '',
    '#include <d3d9.h>',
    '#include <atomic>',
    '',
    '// Reports a D3D9 method the Apple layer does not implement (once per method).',
    'void KisakD3D9_NotImplemented(const char *method);',
    '',
]
total = 0
for iface in INTERFACES:
    methods = parse(iface)
    total += len(methods)
    cls = f'KisakD3D9Default_{iface}'
    lines += [f'class {cls} : public {iface}', '{', 'public:', f'    virtual ~{cls}() = default;', '']
    for ret, name, args in methods:
        if name == 'QueryInterface':
            lines += [f'    {ret} QueryInterface({args}) override', '    {',
                      '        if (ppvObject)', '            *ppvObject = nullptr;',
                      '        return E_NOINTERFACE;', '    }']
            continue
        if name == 'AddRef':
            lines += [f'    {ret} AddRef() override {{ return ++m_refCount; }}']
            continue
        if name == 'Release':
            lines += [f'    {ret} Release() override', '    {', '        const ULONG refs = --m_refCount;',
                      '        if (!refs)', '            delete this;', '        return refs;', '    }']
            continue
        body = f'KisakD3D9_NotImplemented("{iface}::{name}");'
        dr = default_return(ret)
        ret_stmt = f' return {dr};' if dr else ''
        lines.append(f'    {ret} {name}({args}) override {{ {body}{ret_stmt} }}')
    lines += ['', 'protected:', '    std::atomic<ULONG> m_refCount{1};', '};', '']
out.write_text('\n'.join(lines) + '\n')
print(f'wrote {out.relative_to(root.parent.parent.parent)}: {len(INTERFACES)} interfaces, {total} methods')
